app:
  name: practice-env
  port: 8000
database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  name: test


log:
  level: info
  filePath: ./logs
  maxAge: 7
  maxSize: 10
  maxBackups: 10


token:
  secret:
  expiration: 30
